### ISSUE TITLE
Uncaught TypeError: Cannot read property 'overlay' of undefined

### ISSUE THREAD

**Issue by ctf0** [franverona/loadgo#7]
`loadgo.min.js:14 Uncaught TypeError: Cannot read property 'overlay' of undefined`

```html
<div id="loading">
        <div class="l-container">
            <div class="content">
                <img id="logo" src=""logo.png" alt="Logo" class="img-responsive">
            </div>
        </div>
    </div>
```
```scss
#loading {
    position: fixed;
    z-index: 1;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    width: 100vw;
    height: 100vh;
    background-color: white;
    display: table;
    .l-container {
        text-align: center;
        display: table-cell;
        vertical-align: middle;
        .content {
            position: relative;
            width: 25%;
            text-align: center;
            display: inline-block;
        }
    }
}
```

```js
$('#logo').loadgo('setprogress', Pace.start());
```

am trying to do something like ur YT demo but for normal app "not WP" but as ur examples lack suck a thing and ur demo doesnt Explains exactly how so...
